#! /bin/sh
PANEL_FIFO=/tmp/panel-fifo
xsetroot -cursor_name left_ptr

# Basic Configuration
bspc config split_ratio      		0.52
bspc config borderless_monocle 		true
bspc config borderless_monocle   	true
bspc config single_monocle      	true
bspc config gapless_monocle      	true
bspc config focus_by_distance   	true
bspc config focus_follows_pointer   true
bspc config border_width       		1
bspc config window_gap           	5
bspc config focused_border_color    "#f57900"
bspc config active_border_color     "#f57900"
bspc config presel_feedback_color   "#EFF69C"
bspc config normal_border_color     "#ffffff"

bspc rule -a Yad state=floating
# bspc rule -a firefox desktop='^2'
# bspc rule -a TelegramDesktop desktop='^3'
# bspc rule -a Thunar desktop='^4'
# bspc rule -a Geany desktop='^5'
# bspc rule -a Subl desktop='^5'
# bspc rule -a Gimp desktop='^6'

bspc monitor -d "1  " "2  " "3  " "4  " "5  " "6  " "7  " "8  "  "9  " "10  "

# Top panel
bspc config top_padding 21
pkill xmobar ; xmobar $HOME/.config/bspwm/panel/xmobarrc.hs &
pkill trayer ; trayer --edge top --align left --widthtype request --height 21 --alpha 0 --transparent true --monitor primary --width 3 --iconspacing 5 --tint 0xF3E3BD &
pkill sxhkd ; sxhkd &
pkill conky ; (sleep 6 ; conky -c $HOME/.config/bspwm/conky.conkyrc) &

######## DO NOT REMOVE THIS BLOCK ########
if [[ -f "/usr/local/bin/startup" ]]; then
	sh /usr/local/bin/startup
fi
######## DO NOT REMOVE THIS BLOCK ########
